language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
install:
  - sudo apt-get install libboost-program-options-dev libboost-test-dev gcc-4.7 g++-4.7
  - sudo apt-get install cmake
script:
  - mkdir -p build
  - cd build
  - CC="gcc-4.7" CXX="g++-4.7" cmake ..
  - make
